spring:
  application:
    name: ecommerce-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cleanEcomerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    clean-disabled: false
